name: pipeline

on: [push, pull_request]

jobs:
    luacheck:
        name: luacheck
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: Setup Lua
          uses: leafo/gh-actions-lua@v5

        - name: Setup Lua Rocks
          uses: leafo/gh-actions-luarocks@v2

        - name: Install luacheck
          run: luarocks install luacheck

        - name: validate code
          run: luacheck --config .luacheckrc .

    release:
        name: release
        runs-on: ubuntu-latest
        needs: luacheck
        if: contains(github.ref, 'refs/tags')
        steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: echo
          run: echo "would release"

        # - name: wowinterface release
        #   env:
        #     WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        #   run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
